#服务启动端口号
server:
  port: 1111

#服务名称(服务注册到eureka名称)
spring:
  application:
    name: FP-SERVER

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2222/eureka
    #该应用为注册中心，不会注册自己,默认true
    register-with-eureka: true
    #是否需要从eureka上获取注册信息,默认true
    fetch-registry: true